import {
  Type, Heading1, Heading2, Heading3, Heading4, List, ListChecks, CheckSquare,
  ChevronRight, FileText, MessageSquare, Quote, Table2, Clipboard, Link,
  Image, Video, Music, Code, File, Globe, Table, Layout, ImageIcon, Activity,
  LayoutDashboard, Calendar, Clock, MapPin, BarChart3, LineChart, PieChart,
  Hash, FormInput, Database, BookOpen, Edit3, Square, Route, Copy, ToggleLeft,
  Columns2, Columns3, Sparkles, Users, Smile, FolderOpen, ExternalLink,
  GitFork, MapPinned, Pen, FilePlus, Eye, Monitor, Grid3X3, VideoIcon, Workflow, FileArchive,
  type LucideIcon
} from "lucide-react";

// Metadata describing every block type offered in the slash-command /
// insert-block UI. This is a separate taxonomy from `types/blocks.ts`'s
// `Block` union: `Block` models the actual runtime shape a block takes
// once created (discriminated by `type`, with type-specific fields like
// `database`/`table`/`tabs`), whereas this registry is purely UI-facing
// metadata (label/icon/category/shortcut/badge) for every insertable
// block "kind" the editor exposes — including ~30 embed provider ids
// (figma, loom, tweet, etc.) that all collapse to the single
// `embed-generic`-shaped runtime block, and view-only ids (table-view,
// board-view, etc.) that are UI variants of a `database` block, not
// distinct `Block` union members themselves.
export interface BlockRegistryEntry {
  type: string;
  label: string;
  icon: LucideIcon;
  category: string;
  shortcut?: string;
  badge?: string;
}

export const BlockType: Record<string, string> = {
  AI_MEETING_NOTES: "ai-meeting-notes",
  TEXT: "text",
  H1: "h1",
  H2: "h2",
  H3: "h3",
  H4: "h4",
  BULLET: "bullet",
  NUMBER: "number",
  TODO: "todo",
  TOGGLE: "toggle",
  PAGE: "page",
  CALLOUT: "callout",
  QUOTE: "quote",
  TABLE: "table",
  DIVIDER: "divider",
  LINK_TO_PAGE: "link-to-page",
  IMAGE: "image",
  VIDEO: "video",
  AUDIO: "audio",
  CODE: "code",
  FILE: "file",
  BOOKMARK: "bookmark",
  TABLE_VIEW: "table-view",
  BOARD_VIEW: "board-view",
  GALLERY_VIEW: "gallery-view",
  LIST_VIEW: "list-view",
  FEED_VIEW: "feed-view",
  DASHBOARD_VIEW: "dashboard-view",
  CALENDAR_VIEW: "calendar-view",
  TIMELINE_VIEW: "timeline-view",
  MAP_VIEW: "map-view",
  BAR_CHART_V: "bar-chart-v",
  BAR_CHART_H: "bar-chart-h",
  LINE_CHART: "line-chart",
  DONUT_CHART: "donut-chart",
  NUMBER_CHART: "number-chart",
  FORM: "form",
  DATABASE_INLINE: "database-inline",
  DATABASE_FULL: "database-full",
  LINKED_VIEW: "linked-view",
  TABLE_OF_CONTENTS: "table-of-contents",
  BLOCK_EQUATION: "block-equation",
  BUTTON: "button",
  BREADCRUMB: "breadcrumb",
  TABS: "tabs",
  SYNCED_BLOCK: "synced-block",
  TOGGLE_H1: "toggle-h1",
  TOGGLE_H2: "toggle-h2",
  TOGGLE_H3: "toggle-h3",
  COLUMNS_2: "2-columns",
  COLUMNS_3: "3-columns",
  COLUMNS_4: "4-columns",
  COLUMNS_5: "5-columns",
  AI_MEETING: "ai-meeting",
  MERMAID: "mermaid",
  AI_BLOCK: "ai-block",
  MENTION_PERSON: "mention-person",
  MENTION_PAGE: "mention-page",
  DATE_REMINDER: "date-reminder",
  EMOJI: "emoji",
  INLINE_EQUATION: "inline-equation",
  EMBED_GENERIC: "embed-generic",
  GOOGLE_DRIVE: "google-drive",
  TWEET: "tweet",
  GITHUB_GIST: "github-gist",
  GOOGLE_MAPS: "google-maps",
  FIGMA: "figma",
  ABSTRACT: "abstract",
  INVISION: "invision",
  MIXPANEL: "mixpanel",
  FRAMER: "framer",
  WHIMSICAL: "whimsical",
  MIRO: "miro",
  SKETCH: "sketch",
  EXCALIDRAW: "excalidraw",
  PDF: "pdf",
  LOOM: "loom",
  TYPEFORM: "typeform",
  CODEPEN: "codepen",
  REPLIT: "replit",
  HEX: "hex",
  DEEPNOTE: "deepnote",
  TRELLO: "trello",
  DROPBOX_PAPER: "dropbox-paper",
  EVERNOTE: "evernote",
  WORKFLOWY: "workflowy",
  WORD: "word",
  MONDAY: "monday",
  QUIP: "quip",
  ZIP: "zip",
};

export const BlockRegistry: BlockRegistryEntry[] = [
  // 1. Suggested
  { type: "ai-meeting-notes", label: "AI Meeting Notes", icon: Sparkles, category: "Suggested", badge: "Beta" },

  // 2. Basic blocks
  { type: "text", label: "Text", icon: Type, category: "Basic blocks", shortcut: "" },
  { type: "h1", label: "Heading 1", icon: Heading1, category: "Basic blocks", shortcut: "#" },
  { type: "h2", label: "Heading 2", icon: Heading2, category: "Basic blocks", shortcut: "##" },
  { type: "h3", label: "Heading 3", icon: Heading3, category: "Basic blocks", shortcut: "###" },
  { type: "h4", label: "Heading 4", icon: Heading4, category: "Basic blocks", shortcut: "####" },
  { type: "bullet", label: "Bulleted list", icon: List, category: "Basic blocks", shortcut: "-" },
  { type: "number", label: "Numbered list", icon: ListChecks, category: "Basic blocks", shortcut: "1." },
  { type: "todo", label: "To-do list", icon: CheckSquare, category: "Basic blocks", shortcut: "[]" },
  { type: "toggle", label: "Toggle list", icon: ChevronRight, category: "Basic blocks", shortcut: ">" },
  { type: "page", label: "Page", icon: FileText, category: "Basic blocks", shortcut: "" },
  { type: "callout", label: "Callout", icon: MessageSquare, category: "Basic blocks", shortcut: "" },
  { type: "quote", label: "Quote", icon: Quote, category: "Basic blocks", shortcut: "\"" },
  { type: "table", label: "Table", icon: Table2, category: "Basic blocks", shortcut: "" },
  { type: "divider", label: "Divider", icon: Clipboard, category: "Basic blocks", shortcut: "---" },
  { type: "link-to-page", label: "Link to page", icon: Link, category: "Basic blocks", shortcut: "" },

  // 3. Media
  { type: "image", label: "Image", icon: Image, category: "Media" },
  { type: "video", label: "Video", icon: Video, category: "Media" },
  { type: "audio", label: "Audio", icon: Music, category: "Media" },
  { type: "code", label: "Code", icon: Code, category: "Media" },
  { type: "file", label: "File", icon: File, category: "Media" },
  { type: "bookmark", label: "Web bookmark", icon: Globe, category: "Media" },

  // 4. Database
  { type: "table-view", label: "Table view", icon: Table, category: "Database" },
  { type: "board-view", label: "Board view", icon: Layout, category: "Database" },
  { type: "gallery-view", label: "Gallery view", icon: ImageIcon, category: "Database" },
  { type: "list-view", label: "List view", icon: List, category: "Database" },
  { type: "feed-view", label: "Feed view", icon: Activity, category: "Database" },
  { type: "dashboard-view", label: "Dashboard view", icon: LayoutDashboard, category: "Database", badge: "New" },
  { type: "calendar-view", label: "Calendar view", icon: Calendar, category: "Database" },
  { type: "timeline-view", label: "Timeline view", icon: Clock, category: "Database" },
  { type: "map-view", label: "Map view", icon: MapPin, category: "Database", badge: "New" },
  { type: "bar-chart-v", label: "Vertical bar chart", icon: BarChart3, category: "Database" },
  { type: "bar-chart-h", label: "Horizontal bar chart", icon: BarChart3, category: "Database" },
  { type: "line-chart", label: "Line chart", icon: LineChart, category: "Database" },
  { type: "donut-chart", label: "Donut chart", icon: PieChart, category: "Database" },
  { type: "number-chart", label: "Number chart", icon: Hash, category: "Database" },
  { type: "form", label: "Form", icon: FormInput, category: "Database" },
  { type: "database-inline", label: "Database – Inline", icon: Database, category: "Database" },
  { type: "database-full", label: "Database – Full page", icon: Database, category: "Database" },
  { type: "linked-view", label: "Linked view of data source", icon: Link, category: "Database" },

  // 5. Advanced blocks
  { type: "table-of-contents", label: "Table of contents", icon: BookOpen, category: "Advanced blocks" },
  { type: "block-equation", label: "Block equation", icon: Edit3, category: "Advanced blocks" },
  { type: "button", label: "Button", icon: Square, category: "Advanced blocks" },
  { type: "breadcrumb", label: "Breadcrumb", icon: Route, category: "Advanced blocks" },
  { type: "tabs", label: "Tabs", icon: Layout, category: "Advanced blocks", badge: "New" },
  { type: "synced-block", label: "Synced block", icon: Copy, category: "Advanced blocks" },
  { type: "toggle-h1", label: "Toggle heading 1", icon: ToggleLeft, category: "Advanced blocks", shortcut: "#>" },
  { type: "toggle-h2", label: "Toggle heading 2", icon: ToggleLeft, category: "Advanced blocks", shortcut: "##>" },
  { type: "toggle-h3", label: "Toggle heading 3", icon: ToggleLeft, category: "Advanced blocks", shortcut: "###>" },
  { type: "2-columns", label: "2 columns", icon: Columns2, category: "Advanced blocks" },
  { type: "3-columns", label: "3 columns", icon: Columns3, category: "Advanced blocks" },
  { type: "4-columns", label: "4 columns", icon: Columns3, category: "Advanced blocks" },
  { type: "5-columns", label: "5 columns", icon: Columns3, category: "Advanced blocks" },
  { type: "ai-meeting", label: "AI Meeting Notes", icon: Sparkles, category: "Advanced blocks", badge: "Beta" },
  { type: "mermaid", label: "Code – Mermaid", icon: Code, category: "Advanced blocks" },
  { type: "ai-block", label: "AI Block", icon: Sparkles, category: "Advanced blocks" },

  // 6. Inline
  { type: "mention-person", label: "Mention a person", icon: Users, category: "Inline" },
  { type: "mention-page", label: "Mention a page or data source", icon: FileText, category: "Inline" },
  { type: "date-reminder", label: "Date or reminder", icon: Clock, category: "Inline" },
  { type: "emoji", label: "Emoji", icon: Smile, category: "Inline" },
  { type: "inline-equation", label: "Inline equation", icon: Edit3, category: "Inline" },

  // 7. Embeds
  { type: "embed-generic", label: "Embed (generic URL)", icon: Globe, category: "Embeds" },
  { type: "google-drive", label: "Google Drive", icon: FolderOpen, category: "Embeds" },
  { type: "tweet", label: "Tweet / X", icon: ExternalLink, category: "Embeds" },
  { type: "github-gist", label: "GitHub Gist", icon: GitFork, category: "Embeds" },
  { type: "google-maps", label: "Google Maps", icon: MapPinned, category: "Embeds" },
  { type: "figma", label: "Figma", icon: Pen, category: "Embeds" },
  { type: "abstract", label: "Abstract", icon: FilePlus, category: "Embeds" },
  { type: "invision", icon: Eye, label: "Invision", category: "Embeds" },
  { type: "mixpanel", icon: BarChart3, label: "Mixpanel", category: "Embeds" },
  { type: "framer", icon: Monitor, label: "Framer", category: "Embeds" },
  { type: "whimsical", icon: Pen, label: "Whimsical", category: "Embeds" },
  { type: "miro", icon: Grid3X3, label: "Miro", category: "Embeds" },
  { type: "sketch", icon: Pen, label: "Sketch", category: "Embeds" },
  { type: "excalidraw", icon: Pen, label: "Excalidraw", category: "Embeds" },
  { type: "pdf", icon: FileText, label: "PDF", category: "Embeds" },
  { type: "loom", icon: VideoIcon, label: "Loom", category: "Embeds" },
  { type: "typeform", icon: FormInput, label: "Typeform", category: "Embeds" },
  { type: "codepen", icon: Code, label: "CodePen", category: "Embeds" },
  { type: "replit", icon: Code, label: "Replit", category: "Embeds" },
  { type: "hex", icon: Hash, label: "Hex", category: "Embeds" },
  { type: "deepnote", icon: Database, label: "Deepnote", category: "Embeds" },
  { type: "trello", icon: Layout, label: "Trello", category: "Embeds" },
  { type: "dropbox-paper", icon: FolderOpen, label: "Dropbox Paper", category: "Embeds" },
  { type: "evernote", icon: FileText, label: "Evernote", category: "Embeds" },
  { type: "workflowy", icon: Workflow, label: "Workflowy", category: "Embeds" },
  { type: "word", icon: FileText, label: "Word", category: "Embeds" },
  { type: "monday", icon: LayoutDashboard, label: "Monday", category: "Embeds" },
  { type: "quip", icon: FileText, label: "Quip", category: "Embeds" },
  { type: "zip", icon: FileArchive, label: "ZIP", category: "Embeds" },
];
