/**
 * Widget registry — the single source of truth for what this build can
 * render. Powers the picker, the layout normalizer, the config sheets and
 * availability resolution.
 */
import type { WidgetCategory, WidgetDefinition } from "./types";
import {
  MyTasksWidget,
  MY_TASKS_CONFIG_SCHEMA,
  QuickCreateWidget,
  RecentPagesWidget,
  UpcomingTasksWidget,
  StickyNoteWidget,
} from "./widgets/productivity";
import {
  FavoritesWidget,
  PinnedItemsWidget,
  RecentActivityWidget,
  WorkspaceOverviewWidget,
} from "./widgets/workspace";
import {
  AiActivityWidget,
  AiQuickAskWidget,
  AiUsageWidget,
  AiNeuralHubWidget,
  AiInsightsWidget,
  AiWorkspaceHealthWidget,
} from "./widgets/ai";
import {
  AttentionRequiredWidget,
  MentionsWidget,
  UnreadNotificationsWidget,
} from "./widgets/notifications";
import {
  MilestonesWidget,
  ProjectProgressWidget,
  SprintVelocityWidget,
} from "./widgets/projects";
import {
  ConnectionStatusWidget,
  SyncStatusWidget,
  WorldClockWidget,
  AmbientSoundscapesWidget,
} from "./widgets/system";
import { IntegrationsHubWidget } from "./widgets/integrations";
import {
  StreakTrackerWidget,
  FocusTimerWidget,
  ActivityGraphWidget,
  ProgressRingsWidget,
  VitalityBatteryWidget,
  HabitMatrixWidget,
} from "./widgets/gamified";
import {
  WorkspaceKpiWidget,
  TaskVelocityChartWidget,
  ProjectDistributionDonutWidget,
  WeatherWidget,
  DailyQuoteWidget,
  QuickCalculatorWidget,
} from "./widgets/analytics";
import {
  GitHubPrsWidget,
  GitHubIssuesWidget,
  GoogleCalendarWidget,
  GoogleDriveFilesWidget,
  FigmaPreviewWidget,
  ExternalEmbedWidget,
} from "./widgets/connected";
import { ActionButtonsWidget } from "./widgets/automation";

export const WIDGET_CATEGORIES: WidgetCategory[] = [
  "productivity",
  "gamified",
  "ai",
  "workspace",
  "project",
  "analytics",
  "notifications",
  "integrations",
  "automation",
  "system",
  "embed",
];

const DEFINITIONS: WidgetDefinition[] = [
  // ── Productivity ──
  {
    id: "quick-create",
    name: "Quick Create",
    description: "Start a page, task, document, database or AI generation in one click.",
    category: "productivity",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: QuickCreateWidget,
  },
  {
    id: "my-tasks",
    name: "My Tasks",
    description: "Tasks due today, overdue counts and quick complete.",
    category: "productivity",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    defaultConfig: { showOverdue: true, sortBy: "priority" },
    configSchema: MY_TASKS_CONFIG_SCHEMA,
    enabledByDefault: true,
    component: MyTasksWidget,
  },
  {
    id: "upcoming-tasks",
    name: "Upcoming Tasks",
    description: "What's due today, tomorrow and beyond, with quick actions.",
    category: "productivity",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: UpcomingTasksWidget,
  },
  {
    id: "recent-pages",
    name: "Recent Pages",
    description: "Jump back into recently opened or edited pages.",
    category: "productivity",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: RecentPagesWidget,
  },
  {
    id: "sticky-note",
    name: "Sticky Note",
    description: "Tactile pastel notepad for quick brain dumps with one-click page conversion.",
    category: "productivity",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: StickyNoteWidget,
  },

  // ── Gamified & Dynamic Visuals ──
  {
    id: "streak-tracker",
    name: "Streak Tracker",
    description: "Noska daily streak tracker with dynamic 3D flame, weekly shields & celebration particles.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: StreakTrackerWidget,
  },
  {
    id: "focus-timer",
    name: "Liquid Focus Timer",
    description: "Liquid glowing focus ring with 15m Sprint, 25m Deep Work, and 50m Flow modes.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: FocusTimerWidget,
  },
  {
    id: "vitality-battery",
    name: "Vitality Battery",
    description: "Dynamic cognitive energy meter paced by focus sprints and break rhythms.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: VitalityBatteryWidget,
  },
  {
    id: "habit-matrix",
    name: "Daily Habits",
    description: "Track essential daily micro-habits with spring bounce checkmarks.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: HabitMatrixWidget,
  },
  {
    id: "activity-graph",
    name: "Activity Graph",
    description: "Animated bar graph of your pages and tasks touched each day this week.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: ActivityGraphWidget,
  },
  {
    id: "progress-rings",
    name: "Progress Rings",
    description: "Triple dynamic progress rings for pages, tasks, and deep focus.",
    category: "gamified",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: ProgressRingsWidget,
  },

  // ── AI ──
  {
    id: "ai-neural-hub",
    name: "AI Neural Co-Pilot",
    description: "Pulsing 3D neural sphere with soundwave equalizer and quick prompt runner.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: AiNeuralHubWidget,
  },
  {
    id: "ai-insights",
    name: "AI Workspace Insights",
    description: "Autonomous synthesis of recent docs, project velocity, and key blockers.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: AiInsightsWidget,
  },
  {
    id: "ai-health",
    name: "AI Health Diagnostic",
    description: "Real-time sprint velocity score and risk radar for workspace projects.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: AiWorkspaceHealthWidget,
  },
  {
    id: "ai-activity",
    name: "AI Activity",
    description: "Running, completed and failing agents and automations.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: AiActivityWidget,
  },
  {
    id: "ai-quick-ask",
    name: "AI Quick Ask",
    description: "Compact AI prompt entry point for the workspace.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: AiQuickAskWidget,
  },
  {
    id: "ai-usage",
    name: "AI Usage",
    description: "Your requests, tokens and latency at a glance.",
    category: "ai",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: AiUsageWidget,
  },

  // ── Analytics & Metrics ──
  {
    id: "workspace-kpi",
    name: "Tasks KPI Metric",
    description: "Weekly completion progress with delta trend and explainability provenance.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: WorkspaceKpiWidget,
  },
  {
    id: "task-velocity-chart",
    name: "Task Velocity Chart",
    description: "Animated daily velocity bar chart tracking completion volume.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: TaskVelocityChartWidget,
  },
  {
    id: "project-distribution-donut",
    name: "Project Work Donut",
    description: "Breakdown of tasks and pages categorized across workspace projects.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: ProjectDistributionDonutWidget,
  },
  {
    id: "weather",
    name: "Live Weather",
    description: "Local temperature, forecast and atmospheric conditions.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: WeatherWidget,
  },
  {
    id: "daily-quote",
    name: "Daily Motivation",
    description: "Handpicked philosophical quote with one-click copy.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: DailyQuoteWidget,
  },
  {
    id: "quick-calculator",
    name: "Quick Calculator",
    description: "Interactive arithmetic calculator with instantaneous evaluation.",
    category: "analytics",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: QuickCalculatorWidget,
  },

  // ── Connected Provider Widgets ──
  {
    id: "github-prs",
    name: "GitHub Pull Requests",
    description: "Open pull requests, review statuses and CI checks from connected repositories.",
    category: "integrations",
    widgetClass: "connected",
    requiredIntegration: "github",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: GitHubPrsWidget,
  },
  {
    id: "github-issues",
    name: "GitHub Issues",
    description: "Assigned issues, milestone trackers and priority bug triage.",
    category: "integrations",
    widgetClass: "connected",
    requiredIntegration: "github",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: GitHubIssuesWidget,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Upcoming meetings, team events and 1-click Google Meet joins.",
    category: "integrations",
    widgetClass: "connected",
    requiredIntegration: "google",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: GoogleCalendarWidget,
  },
  {
    id: "google-drive",
    name: "Google Drive Recent",
    description: "Recently modified Docs, Sheets, and Presentations.",
    category: "integrations",
    widgetClass: "connected",
    requiredIntegration: "google",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: GoogleDriveFilesWidget,
  },
  {
    id: "figma-preview",
    name: "Figma Live Canvas",
    description: "Interactive Figma prototype and design canvas embed.",
    category: "integrations",
    widgetClass: "embed",
    supportedSizes: ["medium", "large", "wide"],
    defaultSize: "large",
    enabledByDefault: false,
    component: FigmaPreviewWidget,
  },

  // ── Automation ──
  {
    id: "action-buttons",
    name: "Action Hub",
    description: "Custom workflow triggers, build webhooks, and AI prompt shortcuts.",
    category: "automation",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: ActionButtonsWidget,
  },

  // ── Embed ──
  {
    id: "external-embed",
    name: "Sandboxed Web Embed",
    description: "Secure CSP-isolated iframe for external tools, dashboards and prototypes.",
    category: "embed",
    widgetClass: "embed",
    supportedSizes: ["medium", "large", "wide"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: ExternalEmbedWidget,
  },

  // ── Workspace ──
  {
    id: "workspace-overview",
    name: "Workspace Overview",
    description: "Name, pages, tasks and recent activity at a glance.",
    category: "workspace",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large", "wide"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: WorkspaceOverviewWidget,
  },
  {
    id: "recent-activity",
    name: "Recent Activity",
    description: "Edits, comments and task changes across the workspace.",
    category: "workspace",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large", "wide"],
    defaultSize: "wide",
    enabledByDefault: false,
    component: RecentActivityWidget,
  },
  {
    id: "favorites",
    name: "Favorites",
    description: "Your starred pages and documents.",
    category: "workspace",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: true,
    component: FavoritesWidget,
  },
  {
    id: "pinned-items",
    name: "Pinned Items",
    description: "Pin the resources you reach for constantly.",
    category: "workspace",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: PinnedItemsWidget,
  },

  // ── Notifications ──
  {
    id: "unread-notifications",
    name: "Notifications",
    description: "Unread notifications with quick mark-as-read.",
    category: "notifications",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: UnreadNotificationsWidget,
  },
  {
    id: "mentions",
    name: "Mentions",
    description: "Recent comments and mentions of you, one click to jump.",
    category: "notifications",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: MentionsWidget,
  },
  {
    id: "attention-required",
    name: "Attention Required",
    description: "Overdue tasks, failed automations and pending approvals that need you.",
    category: "notifications",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: AttentionRequiredWidget,
  },

  // ── Projects ──
  {
    id: "sprint-velocity",
    name: "Sprint Velocity",
    description: "Sprint completion progress bar and velocity points tracker.",
    category: "project",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: SprintVelocityWidget,
  },
  {
    id: "project-progress",
    name: "Project Progress",
    description: "Completion and health for your project databases.",
    category: "project",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: false,
    component: ProjectProgressWidget,
  },
  {
    id: "milestones",
    name: "Milestones",
    description: "Next milestone, due date and completion count.",
    category: "project",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: MilestonesWidget,
  },

  // ── System & Ambient ──
  {
    id: "world-clock",
    name: "World Clock",
    description: "Analog chronometer with rotating sweep hand and multi-timezone cities.",
    category: "system",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: WorldClockWidget,
  },
  {
    id: "ambient-soundscapes",
    name: "Ambient Soundscapes",
    description: "Lofi rain, deep forest, cozy cafe, and ocean wave sound generator.",
    category: "system",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "medium",
    enabledByDefault: true,
    component: AmbientSoundscapesWidget,
  },
  {
    id: "sync-status",
    name: "Sync Status",
    description: "Whether this workspace is synced, syncing or offline.",
    category: "system",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: SyncStatusWidget,
  },
  {
    id: "connection-status",
    name: "Connection",
    description: "Online and offline indicator.",
    category: "system",
    widgetClass: "native",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: ConnectionStatusWidget,
  },
  {
    id: "integrations-hub",
    name: "Integrations Hub",
    description: "Status and live token health of your connected integrations.",
    category: "integrations",
    widgetClass: "connected",
    supportedSizes: ["small", "medium", "large"],
    defaultSize: "small",
    enabledByDefault: false,
    component: IntegrationsHubWidget,
  },
];

export const WIDGET_REGISTRY: Map<string, WidgetDefinition> = new Map(
  DEFINITIONS.map((def) => [def.id, def]),
);

export function getWidgetDefinition(id: string): WidgetDefinition | undefined {
  return WIDGET_REGISTRY.get(id);
}

export function getAllWidgetDefinitions(): WidgetDefinition[] {
  return DEFINITIONS;
}
