export const TEXT_COLORS = [
  { name: "Default", value: "#ffffff" },
  { name: "Gray", value: "#9e9e9e" },
  { name: "Brown", value: "#a1887f" },
  { name: "Orange", value: "#ffa726" },
  { name: "Yellow", value: "#ffd54f" },
  { name: "Green", value: "#81c784" },
  { name: "Teal", value: "#4db6ac" },
  { name: "Blue", value: "#64b5f6" },
  { name: "Indigo", value: "#7986cb" },
  { name: "Purple", value: "#ba68c8" },
  { name: "Pink", value: "#f06292" },
  { name: "Red", value: "#e57373" },
  { name: "Coral", value: "#ef9a9a" },
  { name: "Rose", value: "#f48fb1" },
  { name: "Lime", value: "#d4e157" },
  { name: "Mint", value: "#aed581" },
  { name: "Sky", value: "#81d4fa" },
  { name: "Lavender", value: "#b39ddb" },
  { name: "Peach", value: "#ffcc80" },
  { name: "Charcoal", value: "#78909c" }
];

export const BG_COLORS = [
  { name: "None", value: "transparent" },
  { name: "Gray", value: "#616161" },
  { name: "Brown", value: "#5d4037" },
  { name: "Orange", value: "#ef6c00" },
  { name: "Yellow", value: "#fbc02d" },
  { name: "Green", value: "#388e3c" },
  { name: "Teal", value: "#00897b" },
  { name: "Blue", value: "#1976d2" },
  { name: "Indigo", value: "#303f9f" },
  { name: "Purple", value: "#7b1fa2" },
  { name: "Pink", value: "#c2185b" },
  { name: "Red", value: "#d32f2f" },
  { name: "Coral", value: "#c62828" },
  { name: "Rose", value: "#ad1457" },
  { name: "Lime", value: "#9e9d24" },
  { name: "Mint", value: "#558b2f" },
  { name: "Sky", value: "#0277bd" },
  { name: "Lavender", value: "#6a1b9a" },
  { name: "Peach", value: "#e65100" },
  { name: "Charcoal", value: "#455a64" }
];
